use raven_agent::agent::runtime::builder::AgentRuntimeBuilder;
use raven_agent::agent::runtime::scheduler::Scheduler;
use raven_agent::event::EventBus;
use raven_agent::executor::Executor;
use raven_agent::executor::ExecutorService;
use raven_agent::llm::SimpleLlm;
use raven_agent::memory::MemoryService;
use raven_agent::planner::ExecutionPlan;
use raven_agent::planner::PlannerService;
use raven_agent::planner::Step;
use raven_agent::reflection::ReflectionService;
use raven_agent::tool::ToolService;
use std::sync::{Arc, Mutex};
use std::thread;

// Note: this file uses crate alias `raven_agent` generated by Cargo package name.

#[test]
fn scheduler_priority_and_topo_order() {
    let mut plan = ExecutionPlan::empty();
    let mut a = Step::new("A".to_string(), "step A".to_string());
    a.priority = 5;
    let mut b = Step::new("B".to_string(), "step B".to_string());
    b.depends_on.push("A".to_string());
    b.priority = 1;
    let mut c = Step::new("C".to_string(), "step C".to_string());
    c.depends_on.push("A".to_string());
    c.priority = 10; // higher priority than B

    plan.steps.push(a);
    plan.steps.push(b);
    plan.steps.push(c);

    let scheduler = Scheduler::new();
    let ordered = scheduler.schedule(&plan).expect("schedule OK");
    // First must be A
    assert_eq!(ordered.steps[0].id, "A");
    // Then C (higher priority) then B
    assert_eq!(ordered.steps[1].id, "C");
    assert_eq!(ordered.steps[2].id, "B");
}

#[test]
fn dispatcher_executor_selection() {
    let bus = Arc::new(EventBus::new());
    let tools = Arc::new(Mutex::new(
        Box::new(ToolService::new()) as Box<dyn raven_agent::tool::ToolManagerService>
    ));
    let planner = Arc::new(PlannerService::new("pl"));
    let memory = Arc::new(Mutex::new(
        Box::new(MemoryService::new()) as Box<dyn raven_agent::memory::MemoryStorage>
    ));
    let llm = Arc::new(SimpleLlm::new());
    let reflection = Arc::new(ReflectionService::new());

    let executor_default: Arc<dyn Executor> = Arc::new(ExecutorService::new(
        memory.clone(),
        tools.clone(),
        llm.clone(),
        planner.clone(),
        bus.clone(),
    ));
    let executor_shell: Arc<dyn Executor> = Arc::new(ExecutorService::new(
        memory.clone(),
        tools.clone(),
        llm.clone(),
        planner.clone(),
        bus.clone(),
    ));

    let builder = AgentRuntimeBuilder::new()
        .with_event_bus(bus.clone())
        .with_planner(planner.clone())
        .with_memory(memory.clone())
        .with_tools(tools.clone())
        .with_llm(llm.clone())
        .with_reflection(reflection.clone())
        .register_executor("default", executor_default.clone())
        .register_executor("shell", executor_shell.clone());

    let runtime = builder.build().expect("build ok");

    // build a plan whose first step requests tool "shell" so dispatcher picks shell executor
    let mut step = Step::new("s1".to_string(), "do shell".to_string());
    step.tool_name = Some("shell".to_string());
    let mut plan = ExecutionPlan::empty();
    plan.steps.push(step);

    let ex = runtime
        .dispatcher()
        .select_executor(&plan)
        .expect("executor found");
    // selection should be the shell executor we registered
    // compare pointers by cloning Arc's strong count or by type info; just check it's not default
    assert!(!Arc::ptr_eq(&ex, &executor_default));
}

struct FlakyExecutor {
    calls: Arc<Mutex<u32>>,
}
impl FlakyExecutor {
    fn new() -> Self {
        Self {
            calls: Arc::new(Mutex::new(0)),
        }
    }
}

impl Executor for FlakyExecutor {
    fn execute_plan(
        &self,
        _plan: &ExecutionPlan,
    ) -> Result<String, raven_agent::error::RavenError> {
        let mut c = self.calls.lock().unwrap();
        *c += 1;
        if *c == 1 {
            Err(raven_agent::error::RavenError::Executor(
                "simulated failure".into(),
            ))
        } else {
            Ok(format!("succeeded in attempt {}", *c))
        }
    }
}

#[test]
fn runtime_retry_via_executor() {
    let bus = Arc::new(EventBus::new());
    let tools = Arc::new(Mutex::new(
        Box::new(ToolService::new()) as Box<dyn raven_agent::tool::ToolManagerService>
    ));
    let planner = Arc::new(PlannerService::new("pl"));
    let memory = Arc::new(Mutex::new(
        Box::new(MemoryService::new()) as Box<dyn raven_agent::memory::MemoryStorage>
    ));
    let llm = Arc::new(SimpleLlm::new());
    let reflection = Arc::new(ReflectionService::new());

    let flaky = Arc::new(FlakyExecutor::new());

    let builder = AgentRuntimeBuilder::new()
        .with_event_bus(bus.clone())
        .with_planner(planner.clone())
        .with_memory(memory.clone())
        .with_tools(tools.clone())
        .with_llm(llm.clone())
        .with_reflection(reflection.clone())
        .register_executor("default", flaky.clone());

    let runtime = builder.build().expect("build ok");

    // create simple plan
    let mut step = Step::new("s1".to_string(), "do something".to_string());
    step.retry_policy.max_attempts = 2;
    let mut plan = ExecutionPlan::empty();
    plan.steps.push(step);

    let res = runtime.run_plan(&plan);
    assert!(res.is_ok());
    assert!(res.unwrap().contains("succeeded"));
}

#[test]
fn concurrent_sessions_run() {
    let bus = Arc::new(EventBus::new());
    let tools = Arc::new(Mutex::new(
        Box::new(ToolService::new()) as Box<dyn raven_agent::tool::ToolManagerService>
    ));
    let planner = Arc::new(PlannerService::new("pl"));
    let memory = Arc::new(Mutex::new(
        Box::new(MemoryService::new()) as Box<dyn raven_agent::memory::MemoryStorage>
    ));
    let llm = Arc::new(SimpleLlm::new());
    let reflection = Arc::new(ReflectionService::new());

    let executor = Arc::new(ExecutorService::new(
        memory.clone(),
        tools.clone(),
        llm.clone(),
        planner.clone(),
        bus.clone(),
    ));

    let builder = AgentRuntimeBuilder::new()
        .with_event_bus(bus.clone())
        .with_planner(planner.clone())
        .with_memory(memory.clone())
        .with_tools(tools.clone())
        .with_llm(llm.clone())
        .with_reflection(reflection.clone())
        .register_executor("default", executor.clone());

    let runtime = Arc::new(builder.build().expect("build ok"));

    let r1 = runtime.clone();
    let r2 = runtime.clone();
    let handle1 = thread::spawn(move || {
        let planner = PlannerService::new("p1");
        let plan = planner
            .create_plan(&raven_agent::intent::Intent {
                name: "t1".into(),
                confidence: 1.0,
                requires_tool: false,
                requires_planner: true,
                metadata: Default::default(),
                raw: "Hello".into(),
            })
            .unwrap();
        r1.run_plan(&plan).unwrap()
    });
    let handle2 = thread::spawn(move || {
        let planner = PlannerService::new("p2");
        let plan = planner
            .create_plan(&raven_agent::intent::Intent {
                name: "t2".into(),
                confidence: 1.0,
                requires_tool: false,
                requires_planner: true,
                metadata: Default::default(),
                raw: "World".into(),
            })
            .unwrap();
        r2.run_plan(&plan).unwrap()
    });

    let o1 = handle1.join().unwrap();
    let o2 = handle2.join().unwrap();
    assert!(!o1.is_empty());
    assert!(!o2.is_empty());
}
